<?php /** @var $block \Magento\Catalog\Block\Product\Image */ ?>

<span class="product-image-container"
      style="width:<?php /* @escapeNotVerified */ echo $block->getWidth()?>px;">
    <span class="product-image-wrapper"
          style="padding-bottom: <?php /* @escapeNotVerified */ echo ($block->getRatio() * 100); ?>%;">
        <img class="product-image-photo lazyload ls-animate ls-zoom"
             <?= $block->escapeHtml($block->getCustomAttributes()) ?>
             src="<?= $block->escapeUrl($block->getImageUrl()) ?>"
             width="<?= $block->escapeHtmlAttr($block->getWidth()) ?>"
             height="<?= $block->escapeHtmlAttr($block->getHeight()) ?>"
             alt="<?= /* @noEscape */ $block->stripTags($block->getLabel(), null, true) ?>" /></span>
</span>
